export const CHAPTERS = [
  { id: 1, name_simple: "Al-Fatihah", name_arabic: "الفاتحة", verses_count: 7, translated_name: { name: "The Opening" } },
  { id: 2, name_simple: "Al-Baqarah", name_arabic: "البقرة", verses_count: 286, translated_name: { name: "The Cow" } },
  { id: 3, name_simple: "Ali 'Imran", name_arabic: "آل عمران", verses_count: 200, translated_name: { name: "Family of Imran" } },
  { id: 4, name_simple: "An-Nisa", name_arabic: "النساء", verses_count: 176, translated_name: { name: "The Women" } },
  { id: 5, name_simple: "Al-Ma'idah", name_arabic: "المائدة", verses_count: 120, translated_name: { name: "The Table Spread" } },
  { id: 6, name_simple: "Al-An'am", name_arabic: "الأنعام", verses_count: 165, translated_name: { name: "The Cattle" } },
  { id: 7, name_simple: "Al-A'raf", name_arabic: "الأعراف", verses_count: 206, translated_name: { name: "The Heights" } },
  { id: 8, name_simple: "Al-Anfal", name_arabic: "الأنفال", verses_count: 75, translated_name: { name: "The Spoils of War" } },
  { id: 9, name_simple: "At-Tawbah", name_arabic: "التوبة", verses_count: 129, translated_name: { name: "The Repentance" } },
  { id: 10, name_simple: "Yunus", name_arabic: "يونس", verses_count: 109, translated_name: { name: "Jonah" } },
  { id: 11, name_simple: "Hud", name_arabic: "هود", verses_count: 123, translated_name: { name: "Hud" } },
  { id: 12, name_simple: "Yusuf", name_arabic: "يوسف", verses_count: 111, translated_name: { name: "Joseph" } },
  { id: 13, name_simple: "Ar-Ra'd", name_arabic: "الرعد", verses_count: 43, translated_name: { name: "The Thunder" } },
  { id: 14, name_simple: "Ibrahim", name_arabic: "ابراهيم", verses_count: 52, translated_name: { name: "Abraham" } },
  { id: 15, name_simple: "Al-Hijr", name_arabic: "الحجر", verses_count: 99, translated_name: { name: "The Rocky Tract" } },
  { id: 16, name_simple: "An-Nahl", name_arabic: "النحل", verses_count: 128, translated_name: { name: "The Bee" } },
  { id: 17, name_simple: "Al-Isra", name_arabic: "الإسراء", verses_count: 111, translated_name: { name: "The Night Journey" } },
  { id: 18, name_simple: "Al-Kahf", name_arabic: "الكهف", verses_count: 110, translated_name: { name: "The Cave" } },
  { id: 19, name_simple: "Maryam", name_arabic: "مريم", verses_count: 98, translated_name: { name: "Mary" } },
  { id: 20, name_simple: "Ta-Ha", name_arabic: "طه", verses_count: 135, translated_name: { name: "Ta-Ha" } },
  { id: 21, name_simple: "Al-Anbya", name_arabic: "الأنبياء", verses_count: 112, translated_name: { name: "The Prophets" } },
  { id: 22, name_simple: "Al-Hajj", name_arabic: "الحج", verses_count: 78, translated_name: { name: "The Pilgrimage" } },
  { id: 23, name_simple: "Al-Mu'minun", name_arabic: "المؤمنون", verses_count: 118, translated_name: { name: "The Believers" } },
  { id: 24, name_simple: "An-Nur", name_arabic: "النور", verses_count: 64, translated_name: { name: "The Light" } },
  { id: 25, name_simple: "Al-Furqan", name_arabic: "الفرقان", verses_count: 77, translated_name: { name: "The Criterion" } },
  { id: 26, name_simple: "Ash-Shu'ara", name_arabic: "الشعراء", verses_count: 227, translated_name: { name: "The Poets" } },
  { id: 27, name_simple: "An-Naml", name_arabic: "النمل", verses_count: 93, translated_name: { name: "The Ant" } },
  { id: 28, name_simple: "Al-Qasas", name_arabic: "القصص", verses_count: 88, translated_name: { name: "The Stories" } },
  { id: 29, name_simple: "Al-Ankabut", name_arabic: "العنكبوت", verses_count: 69, translated_name: { name: "The Spider" } },
  { id: 30, name_simple: "Ar-Rum", name_arabic: "الروم", verses_count: 60, translated_name: { name: "The Romans" } },
  { id: 31, name_simple: "Luqman", name_arabic: "لقمان", verses_count: 34, translated_name: { name: "Luqman" } },
  { id: 32, name_simple: "As-Sajdah", name_arabic: "السجدة", verses_count: 30, translated_name: { name: "The Prostration" } },
  { id: 33, name_simple: "Al-Ahzab", name_arabic: "الأحزاب", verses_count: 73, translated_name: { name: "The Combined Forces" } },
  { id: 34, name_simple: "Saba", name_arabic: "سبأ", verses_count: 54, translated_name: { name: "Sheba" } },
  { id: 35, name_simple: "Fatir", name_arabic: "فاطر", verses_count: 45, translated_name: { name: "Originator" } },
  { id: 36, name_simple: "Ya-Sin", name_arabic: "يس", verses_count: 83, translated_name: { name: "Ya Sin" } },
  { id: 37, name_simple: "As-Saffat", name_arabic: "الصافات", verses_count: 182, translated_name: { name: "Those who set the Ranks" } },
  { id: 38, name_simple: "Sad", name_arabic: "ص", verses_count: 88, translated_name: { name: "The Letter \"Saad\"" } },
  { id: 39, name_simple: "Az-Zumar", name_arabic: "الزمر", verses_count: 75, translated_name: { name: "The Troops" } },
  { id: 40, name_simple: "Ghafir", name_arabic: "غافر", verses_count: 85, translated_name: { name: "The Forgiver" } },
  { id: 41, name_simple: "Fussilat", name_arabic: "فصلت", verses_count: 54, translated_name: { name: "Explained in Detail" } },
  { id: 42, name_simple: "Ash-Shura", name_arabic: "الشورى", verses_count: 53, translated_name: { name: "The Consultation" } },
  { id: 43, name_simple: "Az-Zukhruf", name_arabic: "الزخرف", verses_count: 89, translated_name: { name: "The Ornaments of Gold" } },
  { id: 44, name_simple: "Ad-Dukhan", name_arabic: "الدخان", verses_count: 59, translated_name: { name: "The Smoke" } },
  { id: 45, name_simple: "Al-Jathiyah", name_arabic: "الجاثية", verses_count: 37, translated_name: { name: "The Crouching" } },
  { id: 46, name_simple: "Al-Ahqaf", name_arabic: "الأحقاف", verses_count: 35, translated_name: { name: "The Wind-Curved Sandhills" } },
  { id: 47, name_simple: "Muhammad", name_arabic: "محمد", verses_count: 38, translated_name: { name: "Muhammad" } },
  { id: 48, name_simple: "Al-Fath", name_arabic: "الفتح", verses_count: 29, translated_name: { name: "The Victory" } },
  { id: 49, name_simple: "Al-Hujurat", name_arabic: "الحجرات", verses_count: 18, translated_name: { name: "The Rooms" } },
  { id: 50, name_simple: "Qaf", name_arabic: "ق", verses_count: 45, translated_name: { name: "The Letter \"Qaf\"" } },
  { id: 51, name_simple: "Ad-Dhariyat", name_arabic: "الذاريات", verses_count: 60, translated_name: { name: "The Winnowing Winds" } },
  { id: 52, name_simple: "At-Tur", name_arabic: "الطور", verses_count: 49, translated_name: { name: "The Mount" } },
  { id: 53, name_simple: "An-Najm", name_arabic: "النجم", verses_count: 62, translated_name: { name: "The Star" } },
  { id: 54, name_simple: "Al-Qamar", name_arabic: "القمر", verses_count: 55, translated_name: { name: "The Moon" } },
  { id: 55, name_simple: "Ar-Rahman", name_arabic: "الرحمن", verses_count: 78, translated_name: { name: "The Beneficent" } },
  { id: 56, name_simple: "Al-Waqi'ah", name_arabic: "الواقعة", verses_count: 96, translated_name: { name: "The Inevitable" } },
  { id: 57, name_simple: "Al-Hadid", name_arabic: "الحديد", verses_count: 29, translated_name: { name: "The Iron" } },
  { id: 58, name_simple: "Al-Mujadila", name_arabic: "المجادلة", verses_count: 22, translated_name: { name: "The Pleading Woman" } },
  { id: 59, name_simple: "Al-Hashr", name_arabic: "الحشر", verses_count: 24, translated_name: { name: "The Exile" } },
  { id: 60, name_simple: "Al-Mumtahanah", name_arabic: "الممتحنة", verses_count: 13, translated_name: { name: "She that is to be examined" } },
  { id: 61, name_simple: "As-Saff", name_arabic: "الصف", verses_count: 14, translated_name: { name: "The Ranks" } },
  { id: 62, name_simple: "Al-Jumu'ah", name_arabic: "الجمعة", verses_count: 11, translated_name: { name: "The Congregation, Friday" } },
  { id: 63, name_simple: "Al-Munafiqun", name_arabic: "المنافقون", verses_count: 11, translated_name: { name: "The Hypocrites" } },
  { id: 64, name_simple: "At-Taghabun", name_arabic: "التغابن", verses_count: 18, translated_name: { name: "The Mutual Disillusion" } },
  { id: 65, name_simple: "At-Talaq", name_arabic: "الطلاق", verses_count: 12, translated_name: { name: "The Divorce" } },
  { id: 66, name_simple: "At-Tahrim", name_arabic: "التحريم", verses_count: 12, translated_name: { name: "The Prohibition" } },
  { id: 67, name_simple: "Al-Mulk", name_arabic: "الملك", verses_count: 30, translated_name: { name: "The Sovereignty" } },
  { id: 68, name_simple: "Al-Qalam", name_arabic: "القلم", verses_count: 52, translated_name: { name: "The Pen" } },
  { id: 69, name_simple: "Al-Haqqah", name_arabic: "الحاقة", verses_count: 52, translated_name: { name: "The Reality" } },
  { id: 70, name_simple: "Al-Ma'arij", name_arabic: "المعارج", verses_count: 44, translated_name: { name: "The Ascending Stairways" } },
  { id: 71, name_simple: "Nuh", name_arabic: "نوح", verses_count: 28, translated_name: { name: "Noah" } },
  { id: 72, name_simple: "Al-Jinn", name_arabic: "الجن", verses_count: 28, translated_name: { name: "The Jinn" } },
  { id: 73, name_simple: "Al-Muzzammil", name_arabic: "المزمل", verses_count: 20, translated_name: { name: "The Enshrouded One" } },
  { id: 74, name_simple: "Al-Muddaththir", name_arabic: "المدثر", verses_count: 56, translated_name: { name: "The Cloaked One" } },
  { id: 75, name_simple: "Al-Qiyamah", name_arabic: "القيامة", verses_count: 40, translated_name: { name: "The Resurrection" } },
  { id: 76, name_simple: "Al-Insan", name_arabic: "الانسان", verses_count: 31, translated_name: { name: "The Man" } },
  { id: 77, name_simple: "Al-Mursalat", name_arabic: "المرسلات", verses_count: 50, translated_name: { name: "The Emissaries" } },
  { id: 78, name_simple: "An-Naba", name_arabic: "النبأ", verses_count: 40, translated_name: { name: "The Tidings" } },
  { id: 79, name_simple: "An-Nazi'at", name_arabic: "النازعات", verses_count: 46, translated_name: { name: "Those who drag forth" } },
  { id: 80, name_simple: "Abasa", name_arabic: "عبس", verses_count: 42, translated_name: { name: "He Frowned" } },
  { id: 81, name_simple: "At-Takwir", name_arabic: "التكوير", verses_count: 29, translated_name: { name: "The Overthrowing" } },
  { id: 82, name_simple: "Al-Infitar", name_arabic: "الإنفطار", verses_count: 19, translated_name: { name: "The Cleaving" } },
  { id: 83, name_simple: "Al-Mutaffifin", name_arabic: "المطففين", verses_count: 36, translated_name: { name: "The Defrauding" } },
  { id: 84, name_simple: "Al-Inshiqaq", name_arabic: "الإنشقاق", verses_count: 25, translated_name: { name: "The Sundering" } },
  { id: 85, name_simple: "Al-Buruj", name_arabic: "البروج", verses_count: 22, translated_name: { name: "The Mansions of the Stars" } },
  { id: 86, name_simple: "At-Tariq", name_arabic: "الطارق", verses_count: 17, translated_name: { name: "The Nightcommer" } },
  { id: 87, name_simple: "Al-A'la", name_arabic: "الأعلى", verses_count: 19, translated_name: { name: "The Most High" } },
  { id: 88, name_simple: "Al-Ghashiyah", name_arabic: "الغاشية", verses_count: 26, translated_name: { name: "The Overwhelming" } },
  { id: 89, name_simple: "Al-Fajr", name_arabic: "الفجر", verses_count: 30, translated_name: { name: "The Dawn" } },
  { id: 90, name_simple: "Al-Balad", name_arabic: "البلد", verses_count: 20, translated_name: { name: "The City" } },
  { id: 91, name_simple: "Ash-Shams", name_arabic: "الشمس", verses_count: 15, translated_name: { name: "The Sun" } },
  { id: 92, name_simple: "Al-Layl", name_arabic: "الليل", verses_count: 21, translated_name: { name: "The Night" } },
  { id: 93, name_simple: "Ad-Duhaa", name_arabic: "الضحى", verses_count: 11, translated_name: { name: "The Morning Hours" } },
  { id: 94, name_simple: "Ash-Sharh", name_arabic: "الشرح", verses_count: 8, translated_name: { name: "The Relief" } },
  { id: 95, name_simple: "At-Tin", name_arabic: "التين", verses_count: 8, translated_name: { name: "The Fig" } },
  { id: 96, name_simple: "Al-Alaq", name_arabic: "العلق", verses_count: 19, translated_name: { name: "The Clot" } },
  { id: 97, name_simple: "Al-Qadr", name_arabic: "القدر", verses_count: 5, translated_name: { name: "The Power" } },
  { id: 98, name_simple: "Al-Bayyinah", name_arabic: "البينة", verses_count: 8, translated_name: { name: "The Clear Proof" } },
  { id: 99, name_simple: "Az-Zalzalah", name_arabic: "الزلزلة", verses_count: 8, translated_name: { name: "The Earthquake" } },
  { id: 100, name_simple: "Al-Adiyat", name_arabic: "العاديات", verses_count: 11, translated_name: { name: "The Courser" } },
  { id: 101, name_simple: "Al-Qari'ah", name_arabic: "القارعة", verses_count: 11, translated_name: { name: "The Calamity" } },
  { id: 102, name_simple: "At-Takathur", name_arabic: "التكاثر", verses_count: 8, translated_name: { name: "The Rivalry in world increase" } },
  { id: 103, name_simple: "Al-Asr", name_arabic: "العصر", verses_count: 3, translated_name: { name: "The Declining Day" } },
  { id: 104, name_simple: "Al-Humazah", name_arabic: "الهمزة", verses_count: 9, translated_name: { name: "The Traducer" } },
  { id: 105, name_simple: "Al-Fil", name_arabic: "الفيل", verses_count: 5, translated_name: { name: "The Elephant" } },
  { id: 106, name_simple: "Quraysh", name_arabic: "قريش", verses_count: 4, translated_name: { name: "Quraysh" } },
  { id: 107, name_simple: "Al-Ma'un", name_arabic: "الماعون", verses_count: 7, translated_name: { name: "The Small Kindnesses" } },
  { id: 108, name_simple: "Al-Kawthar", name_arabic: "الكوثر", verses_count: 3, translated_name: { name: "The Abundance" } },
  { id: 109, name_simple: "Al-Kafirun", name_arabic: "الكافرون", verses_count: 6, translated_name: { name: "The Disbelievers" } },
  { id: 110, name_simple: "An-Nasr", name_arabic: "النصر", verses_count: 3, translated_name: { name: "The Divine Support" } },
  { id: 111, name_simple: "Al-Masad", name_arabic: "المسد", verses_count: 5, translated_name: { name: "The Palm Fiber" } },
  { id: 112, name_simple: "Al-Ikhlas", name_arabic: "الإخلاص", verses_count: 4, translated_name: { name: "The Sincerity" } },
  { id: 113, name_simple: "Al-Falaq", name_arabic: "الفلق", verses_count: 5, translated_name: { name: "The Daybreak" } },
  { id: 114, name_simple: "An-Nas", name_arabic: "الناس", verses_count: 6, translated_name: { name: "The Mankind" } }
];
